import exp from 'constants';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

type Time = {
  datetime: string;
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'To Do App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const res = await fetch(
      'http://worldtimeapi.org/api/timezone/America/Chicago',
      {
        next: {
          revalidate: 5,
        }
      }
    );
    const data: Time = await res.json()
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-800 text-slate-100 container mx-auto p-4`}>
      <h1 className="font-bold text-3xl text-white-400">{data.datetime}</h1>{children}</body>
    </html>
  )
}
