import { Metadata } from "next"

export async function generateMetaData({params}: {params: {id: string}}){
    return {
        title: 'My post'
    }
  }

export const metadata: Metadata = {
    title: 'To Do App',
    description: 'Generated by create next app',
}

export default function Page({params}: {params: {id: string}}){
    return <h1>ID: {params.id}</h1>
}